# Run Radar CLI scan via Azure Pipelines

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Radar CLI

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: npm i -g @eurekadevsecops/radar
  displayName: Install Radar CLI

- script: radar && radar scanners
  displayName: Verify Radar install

- script: radar scan
  displayName: Run Radar scan
