[[scanners]]
name = "depscan"
title = "OWASP dep-scan"
description = "Next-generation security and risk audit tool."
categories = [ "SCA" ]
cmd = "${assets}/run.sh ${target} ${assets} ${output}"

[[scanners]]
name = "opengrep"
title = "Opengrep"
description = "Ultra-fast static analysis tool."
categories = [ "SAST" ]
cmd = "${assets}/run.sh ${target} ${assets} ${output}"

[[scanners]]
name = "gitleaks"
title = "Gitleaks"
description = "Detect secrets like passwords, API keys, and tokens in source code."
categories = [ "SAST" ]
cmd = "${assets}/run.sh ${target} ${assets} ${output}"
